### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ctw452002** [jasonwynn10/MiniBosses#3]
27.07 05:36:22 [Server] Server thread/CRITICAL Unhandled exception executing command 'minibosses create 11 zombie' in minibosses: Call to a member function getInt() on null
27.07 05:36:22 [Server] Server thread/CRITICAL Error: "Call to a member function getInt() on null" (EXCEPTION) in "MiniBosses-master/src/MiniBosses/Boss" at line 54

**Comment by ctw452002** [comment]
@jasonwynn10

**Comment by jasonw4331** [comment]
duplicate of #1
